name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so that annotate_pr_with_ruff can access it.
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install ruff from PyPI
        uses: install-pinned/ruff@66c987de12929f701b73e83c82edc36050ae55a0
      - name: Install requests library
        run: pip install requests==2.28.1
        shell: bash
      - name: annotate_pr_with_ruff
        uses: EnriqueSoria/annotate_pr_with_ruff@v0.1.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: |
          echo "::set-output name=num_errors::3"
          echo "::error file=src/main.py,line=8::That was an error"
          echo "::error file=src/main.py,line=8,col=1::That was an error on col 1"
          echo "${{ steps.annotate_pr_with_ruff.num_errors }}" >> $GITHUB_STEP_SUMMARY
        shell: bash
      - name: test2
        run: cat $GITHUB_STATE && cat $GITHUB_STATE >> $GITHUB_STEP_SUMMARY
